// <auto-generated />
using GymApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240627012534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymApi.Models.Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("Nivelconta")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_MEMBERS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = 3,
                            Email = "brad@gmail.com",
                            Nivelconta = 10,
                            Nome = "Brad"
                        },
                        new
                        {
                            Id = 2,
                            Classe = 2,
                            Email = "bruno@gmail.com",
                            Nivelconta = 8,
                            Nome = "Bruno"
                        },
                        new
                        {
                            Id = 3,
                            Classe = 3,
                            Email = "eduardo@gmail.com",
                            Nivelconta = 6,
                            Nome = "Eduardo"
                        },
                        new
                        {
                            Id = 4,
                            Classe = 1,
                            Email = "vitor@gmail.com",
                            Nivelconta = 4,
                            Nome = "Vitor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
